package ng.optisoft.rosabon.enums;

public enum  RoleConstant {
    INDIVIDUAL_USER,
    COMPANY,
    ADMINISTRATOR,
    SUPER_ADMINISTRATOR,
    ROLE_TRIAL,
    WITHDRAWAL_REVIEWER,
    WITHDRAWAL_REVIEWER_1,
    WITHDRAWAL_REVIEWER_2,
    WITHDRAWAL_REVIEWER_3,
    WITHDRAWAL_REVIEWER_4,
    WITHDRAWAL_APPROVER,
}
