package ng.optisoft.rosabon.enums;

public enum TransactionType {
   NEW_INVESTMENT_BACKEND,
   TOPUP_BACKEND,
   TRANSFER_BACKEND,
   ROLLOVER_BACKEND,
   PART_WITHDRAWAL_TO_BANK_BACKEND,
   FULL_WITHDRAWAL_TO_BANK_BACKEND,
   PART_WITHDRAWAL_TO_BANK_FRONTEND,
   FULL_WITHDRAWAL_TO_BANK_FRONTEND,
   PART_WITHDRAWAL_FROM_WALLET_TO_BANK_FRONTEND,
   FULL_WITHDRAWAL_FROM_WALLET_TO_BANK_FRONTEND
}
