package ng.optisoft.rosabon.enums;

public enum TrTransactionHistoryDescription {
    FUND_PLACED, PLAN_TOP_UP, PART_WITHDRAWAL, FULL_WITHDRAWAL, INTEREST_EARNED, WITHDRAWAL_TO_WALLET,
    PLAN_ROLL_OVER, PENALTY_CHARGE, WITHOLDING_TAX, TRANSFER, UPFRONT_INTEREST_PAYOUT_TO_WALLET,
    MONTHLY_INTEREST_PAYOUT_TO_WALLET, QUARTERLY_INTEREST_PAYOUT_TO_WALLET, INTEREST_PAYOUT_TO_WALLET,
    UPFRONT_INTEREST_EARNED,
    QUARTERLY_INTEREST_EARNED,
    MONTHLY_INTEREST_EARNED,
    INITIAL_INVESTMENT,
    WITHDRAWAL_TO_BANK,
    REVERSAL,
    WITHHOLDING_TAX
}
